# K Nearest Neighbor (KNN)

KNN is a instance based algorithm where unlike most machine learning algorithms, it does not train on the data. It stores the dataset and calculates the distance between new points and all the training points during testing. It finds the k nearest points present in the dataset takes the mode (for classification) or the mean (for regression) of the k nearest points as the result

# KNN Implementation

## Exploring dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [2]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

## Train on Age and Estimated Salary to classify if purchased or not

In [3]:
X = df.iloc[:, [2, 3]].values  # Age and EstimatedSalary
y = df.iloc[:, -1].values      # Purchased (0 or 1)

In [4]:
# Split into Training and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

# Predict the Test set results
y_pred = classifier.predict(X_test)

## Result

In [12]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
 [[64  4]
 [ 3 29]]
Accuracy: 93.00%

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

## Comparing with Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

classifier_lr = LogisticRegression(random_state=0, solver='liblinear')

classifier_lr.fit(X_train, y_train)

# Predict the results
y_pred_lr = classifier_lr.predict(X_test)

In [11]:
print("Logistic Regression Results")
print(confusion_matrix(y_test, y_pred_lr))
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr)* 100:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

Logistic Regression Results
[[65  3]
 [ 8 24]]
Accuracy: 89.00

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100

KNN performed 4% better than logistic regression